#!/bin/sh
set -eu

if [ -f /out/deployments.env ]; then
    set -a
    # shellcheck disable=SC1091
    . /out/deployments.env
    set +a
fi
if [ -f /demo/demo.env ]; then
    set -a
    # shellcheck disable=SC1091
    . /demo/demo.env
    set +a
fi

: "${EEZ_UI_NETWORK_NAME:=EEZ network}"
: "${EEZ_UI_ENCLAVE:=standalone}"
: "${EEZ_UI_PROTOCOL_COMMIT:=development}"
: "${EEZ_REGISTRY_ADDRESS:=}"
: "${EEZL2_ADDRESS:=}"
: "${EEZ_ECDSA_PROOF_SYSTEM_ADDRESS:=}"
: "${EEZ_ROLLUP_MANAGER_ADDRESS:=}"
: "${EEZ_L1_BRIDGE_SENDER:=}"
: "${EEZ_L2_BRIDGE_RECEIVER:=}"
: "${EEZ_ROLLUP_ID:=1}"
: "${EEZ_UI_L1_EXPLORER_URL:=}"
: "${EEZ_UI_L2_EXPLORER_URL:=}"
: "${EEZ_UI_L2_EXPLORER_API_URL:=}"
: "${EEZ_UI_DEMO_ENABLED:=false}"
: "${EEZ_UI_DEMO_ACCOUNT_ADDRESS:=}"
: "${EEZ_UI_DEMO_PRIVATE_KEY:=}"
: "${EEZ_UI_DEMO_BRIDGE_ADDRESS:=}"
: "${EEZ_UI_DEMO_TOKEN_ADDRESS:=}"
: "${EEZ_UI_DEMO_POOL_ADDRESS:=}"
: "${EEZ_UI_DEMO_EXECUTOR_L1:=}"
: "${EEZ_UI_DEMO_EXECUTOR_L2:=}"
: "${EEZ_UI_DEMO_WRAPPED_TOKEN_L2:=}"
: "${EEZ_UI_DEMO_NFT_L2:=}"
: "${EEZ_UI_FAUCET_ADDRESS:=${FAUCET_ADDRESS:-}}"
: "${EEZ_UI_REVERSE_EXECUTOR_L2:=${REVERSE_EXECUTOR_L2:-}}"
: "${EEZ_UI_REVERSE_NFT_L1:=${REVERSE_NFT_L1:-}}"
: "${EEZ_UI_REVERSE_EXECUTOR_L1:=${REVERSE_EXECUTOR_L1:-}}"
: "${EEZ_UI_AGG_WETH_ADDRESS:=${AGG_WETH_ADDRESS:-}}"
: "${EEZ_UI_AGG_USDC_ADDRESS:=${AGG_USDC_ADDRESS:-}}"
: "${EEZ_UI_AGG_L1_AMM_ADDRESS:=${AGG_L1_AMM_ADDRESS:-}}"
: "${EEZ_UI_AGG_AGGREGATOR_ADDRESS:=${AGG_AGGREGATOR_ADDRESS:-}}"
: "${EEZ_UI_AGG_L2_EXECUTOR_ADDRESS:=${AGG_L2_EXECUTOR_ADDRESS:-}}"
: "${EEZ_UI_AGG_L2_AMM_ADDRESS:=${AGG_L2_AMM_ADDRESS:-}}"
: "${EEZ_UI_AGG_L2_EXECUTOR_PROXY_ADDRESS:=${AGG_L2_EXECUTOR_PROXY_ADDRESS:-}}"
: "${EEZ_UI_AGG_WRAPPED_WETH_L2:=${AGG_WRAPPED_WETH_L2:-}}"
: "${EEZ_UI_AGG_WRAPPED_USDC_L2:=${AGG_WRAPPED_USDC_L2:-}}"

export EEZ_UI_NETWORK_NAME EEZ_UI_ENCLAVE EEZ_UI_PROTOCOL_COMMIT
export EEZ_REGISTRY_ADDRESS EEZL2_ADDRESS EEZ_ECDSA_PROOF_SYSTEM_ADDRESS
export EEZ_ROLLUP_MANAGER_ADDRESS EEZ_L1_BRIDGE_SENDER EEZ_L2_BRIDGE_RECEIVER EEZ_ROLLUP_ID
export EEZ_UI_L1_EXPLORER_URL EEZ_UI_L2_EXPLORER_URL EEZ_UI_L2_EXPLORER_API_URL
export EEZ_UI_DEMO_ENABLED EEZ_UI_DEMO_ACCOUNT_ADDRESS EEZ_UI_DEMO_PRIVATE_KEY
export EEZ_UI_DEMO_BRIDGE_ADDRESS EEZ_UI_DEMO_TOKEN_ADDRESS EEZ_UI_DEMO_POOL_ADDRESS
export EEZ_UI_DEMO_EXECUTOR_L1 EEZ_UI_DEMO_EXECUTOR_L2 EEZ_UI_DEMO_WRAPPED_TOKEN_L2
export EEZ_UI_DEMO_NFT_L2 EEZ_UI_FAUCET_ADDRESS
export EEZ_UI_REVERSE_EXECUTOR_L2 EEZ_UI_REVERSE_NFT_L1 EEZ_UI_REVERSE_EXECUTOR_L1
export EEZ_UI_AGG_WETH_ADDRESS EEZ_UI_AGG_USDC_ADDRESS EEZ_UI_AGG_L1_AMM_ADDRESS
export EEZ_UI_AGG_AGGREGATOR_ADDRESS EEZ_UI_AGG_L2_EXECUTOR_ADDRESS EEZ_UI_AGG_L2_AMM_ADDRESS
export EEZ_UI_AGG_L2_EXECUTOR_PROXY_ADDRESS EEZ_UI_AGG_WRAPPED_WETH_L2 EEZ_UI_AGG_WRAPPED_USDC_L2

envsubst < /opt/eez/config.template.json > /usr/share/nginx/html/config.json
