#!/usr/bin/env python3
"""Snapshot debugger ABIs from compiled eez-core-protocol artifacts."""
import copy
import json
from pathlib import Path
import subprocess
import sys

root = Path(__file__).resolve().parent.parent
protocol = Path(sys.argv[1]) if len(sys.argv) > 1 else root.parent / "eez-core-protocol"
revision = subprocess.check_output(["git", "-C", str(protocol), "rev-parse", "HEAD"], text=True).strip()

def clean(value):
    if isinstance(value, dict):
        return {k: clean(v) for k, v in value.items() if k != "internalType"}
    if isinstance(value, list):
        return [clean(v) for v in value]
    return value

def event(name, inputs):
    return {"type": "event", "name": name, "inputs": inputs, "anonymous": False}

def field(name, type_, indexed=False):
    return {"name": name, "type": type_, "indexed": indexed}

output = [f"// Generated by scripts/generate-visualizer-abi.py; protocol {revision}.",
          "// Includes the deployed pre-cursor L2 static-table ABI and earlier EEZ event forms."]
for contract, name in [("EEZ", "eezL1Abi"), ("EEZL2", "eezL2Abi")]:
    artifact = protocol / "out" / f"{contract}.sol" / f"{contract}.json"
    abi = [clean(x) for x in json.loads(artifact.read_text())["abi"] if x["type"] in ("event", "error", "function")]
    if contract == "EEZL2":
        for item in list(abi):
            if item.get("name") in ("loadExecutionTable", "executeIncomingCrossChainCall", "ExecutionTableLoaded"):
                old = copy.deepcopy(item)
                static = old["inputs"][1]["components"]
                if static[0]["name"] == "expectedEntryIndex":
                    static.pop(0)
                    abi.append(old)
    else:
        abi.extend([
            event("BatchPosted", [field("rollupCount", "uint256", True)]),
            event("BatchPosted", [field("rollupCount", "uint256")]),
            event("L2ExecutionPerformed", [field("rollupId", "uint64", True), field("newRoot", "bytes32")]),
        ])
    output.append(f"export const {name} = [")
    output.extend("  " + json.dumps(item, separators=(",", ":")) + "," for item in abi)
    output.append("] as const;\n")
(root / "src/abi/eez.ts").write_text("\n".join(output))
